### ISSUE TITLE
[BUG] 将小红书Xsxt代码会报错，其他代码不会

### ISSUE THREAD

**Issue by ElieenAndBella** [ylw00/qxVm#1]
![image](https://github.com/ylw00/qxVm/assets/54427695/bd48b28f-28ee-4beb-9788-a265e6cc2202)

**Comment by ElieenAndBella** [comment]
大佬后续会开源最新的吗

**Comment by Xizike** [comment]
你这属于使用文档没看明白了，建议好好看看

**Comment by ylw00** [comment]
你要调试下看看是不是内部代码异常中止了

**Comment by ylw00** [comment]
目前不会开源最新的, 不过后续可以把debugger,改为日志打印
