### ISSUE TITLE
RTCPeerConnection  怎么使用

### ISSUE THREAD

**Issue by BadDeveloper2022** [ylw00/qxVm#2]
`var ip= '127.0.0.1';
function _fake_rpc(servers) {
    this.servers = servers;
    this.localDescription = {sdp: "a=candidate:" + ip};
    this.createDataChannel = function (e) {
        console.log('createDataChannel=>',e);
    };
    this.createOffer = function (cb) {
        console.log('createOffer=>',cb);
    }
}

RTCPeerConnection = new Proxy(_fake_rpc, {
    construct: (targ, args, newTarget) => {
        return new Proxy(new targ(args[0], args[1]), {
            set: (targ, p, v) => {
                console.log('RTCPeerConnection===>'+p);
                if (p == "onicecandidate") v({candidate: {candidate: targ.localDescription.sdp}})
            }
        })
    }
});`

**Comment by ylw00** [comment]
QQ: 2783693683




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ylw00/qxVm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月7日(星期三) 上午10:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ylw00/qxVm] RTCPeerConnection  怎么使用 (Issue #2)





 
`var ip= '127.0.0.1';
 function _fake_rpc(servers) {
 this.servers = servers;
 this.localDescription = {sdp: "a=candidate:" + ip};
 this.createDataChannel = function (e) {
 console.log('createDataChannel=&gt;',e);
 };
 this.createOffer = function (cb) {
 console.log('createOffer=&gt;',cb);
 }
 }
 
RTCPeerConnection = new Proxy(_fake_rpc, {
 construct: (targ, args, newTarget) =&gt; {
 return new Proxy(new targ(args[0], args[1]), {
 set: (targ, p, v) =&gt; {
 console.log('RTCPeerConnection===&gt;'+p);
 if (p == "onicecandidate") v({candidate: {candidate: targ.localDescription.sdp}})
 }
 })
 }
 });`
